services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app/main.py
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - ./backend:/app
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - mynetwork

networks:
  mynetwork:
