services:
  app:
    build:
      context: ./backend
    environment:
      FLASK_APP: app/main.py
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - ./backend:/app
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    networks:
      - mynetwork

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mynetwork
    depends_on:
      - app
      - frontend

networks:
  mynetwork: